[package]
name = "rust-logger"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
keywords = ["debugging", "text", "logging"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
repository = "https://github.com/mrborghini/rust-logger"

[dependencies]
chrono = "0.4"
